[frontend]
url = "http://localhost:3000"

[backend]
port = 7878

[db]
surrealdb_host = "localhost:10086"
surrealdb_root_name = "root"
surrealdb_root_password = "root"
surrealdb_namespace = "apps"
surrealdb_database = "backend"
redis_host = "redis://127.0.0.1/"

[jwt]
access_token_secret = "J7uHMe5O001ekwczxhxRgeaMb/7DURzepv7mVDi0VXg="
access_token_expires_in = 900
